### ISSUE TITLE
Zed Camera Computer Vision

### ISSUE THREAD

**Issue by w29ahmed** [uwrobotics/RR2019-Hummingbot-Software#15]
The Zed Camera needs to provide 2 essential features:

- Depth thresholding to crop out traffic light/sign from an image, which will be essential for our traffic sign and light processing as it becomes way easier if we can provide an image to those functions with only the thing they are intersted in 

- Cropping out the ground plane: Will help lane and endline detection algorithms 

The basic idea should be to use the depth map and the image feeds from the zed, do some processing, and output the processed frames to our own custom topic that the computer vision node can subscribe to and run it's processing on

**Comment by w29ahmed** [comment]
This paper might be worth investigating: 
https://ieeexplore.ieee.org/document/6130371

**Comment by simeng-yang** [comment]
https://docs.opencv.org/3.2.0/dd/d53/tutorial_py_depthmap.html

**Comment by w29ahmed** [comment]
Quick update on this: There is little to no value in using the depth map to extract the ground plane. It's main use case was to help with lane detection, but lane detection does a warp transform on the ground plane anyways and thus anything not seen within the lanes won't be considered in lane detection anyways. I didn't know the full details of our lane detection at the time which is why I suggested that. 

It would still be super useful for cropping out sign and traffic light though!

**Comment by w29ahmed** [comment]
Ok so we didn't really end up doing anything with the zed depth map. Cropping out the ground plane wouldn't help up being too helpful because a) traffic light performs a perspective transform so the sky gets cropped out that anyways. And endline still works fine and don't think ground cropping would contribute much to the accuracy.

Depth cropping for the traffic light would still be useful, maybe next year. Traffic sign uses a haar cascade to find the traffic sign and does some image processing to extract the arrow, so again not needed for that either. 

Stereo cameras are still cool, maybe we'll try to do something with it next year?
