### ISSUE TITLE
Traffic Light Detection

### ISSUE THREAD

**Issue by w29ahmed** [uwrobotics/RR2019-Hummingbot-Software#17]
Traffic light detection is likely going to be seeing a large cut down and simplification 

Last year's codebase used YOLO object detection with an image classifier called darknet to detect and get a bounding box around the traffic light. Once the bounding box was found, this region was cropped out of the image and fed into a computer vision algorithm that would figure out when the traffic light would go from red -> green based on colour thresholding.

This year, we would like to cut out the YOLO object detection completely, and take advantage of the depth man to detect the traffic sign (as all the pixels on the traffic sign should be very similar in depth), to get an image of just the traffic sign cropped out, and then run the same algorithm from last year on that image to detect from the traffic light goes green.

Ideally, this task should just involve moving over the color detection algorithm and cut out all the darknet from last year's codebase. And then it's a matter of waiting until we get zed depth thresholding implemented and test the traffic light algorithm with that!

**Comment by y556zhao** [comment]
New way of traffic light detection:
1. only filter color red.
2. find contours in each frame and determine if the shape of a contour is circle. (also use buffer)
3. ......
