### ISSUE TITLE
Endline Detection

### ISSUE THREAD

**Issue by w29ahmed** [uwrobotics/RR2019-Hummingbot-Software#18]
This task should simply involve moving over the endline detection code from last year. The main difference from the endline's perspective this year will be that it should run the algorithm on a processed image feed from the zed camera that only includes the ground plane, which should reduce some noise and give better results (eg. somebody standing wearing magenta shoes would get caught in the thresholding)

**Comment by w29ahmed** [comment]
![left0000](https://user-images.githubusercontent.com/29009445/58055236-16edbc80-7b2b-11e9-9d42-55ba6f5d60b7.jpg)
![left0002](https://user-images.githubusercontent.com/29009445/58055237-18b78000-7b2b-11e9-8495-c4e117270236.jpg)

Just tested out last year's codebase and it doesn't look great. 

I'm gonna try to play with the thresholding parameters and get it to look better and see how well it works, and Allan is researching adaptive thresholding techniques we can use to try and make it better, since the thresholding values are hardcoded and lighting conditions can easily throw it off (which is what i'm assuming is happening here)

**Comment by w29ahmed** [comment]
![left0000](https://user-images.githubusercontent.com/29009445/58363616-14fe6300-7e75-11e9-8011-7bcbeda005ff.jpg)
![left0001](https://user-images.githubusercontent.com/29009445/58363618-17f95380-7e75-11e9-96ac-f6ecd59e424a.jpg)


![tesst](https://user-images.githubusercontent.com/29009445/58363631-424b1100-7e75-11e9-80cb-b3fce24d3fe4.jpg)
![teest](https://user-images.githubusercontent.com/29009445/58363632-44ad6b00-7e75-11e9-8130-0f24fddf70d1.jpg)

Went back and tuned the thresholding to do a better job, turns out last year code was only accounting for hue and not even looking at the saturation and value channels (?), hue range was a little off aswell, but this looks much better!

**Comment by w29ahmed** [comment]
Last year's code is using blob detection to figure out when it actually sees a lane, and from this rosbag it leads to quite a few false positives, a small piece of noise gets caught in the blob detection and triggers it, which is definitely no good.

I think the algorithm for detecting the endline from that thresholded image should be something like this:
1. Find contours in the image 
2. Sort contours from largest to least area, and just take the largest area from this list (assume all the other contours are just noise, the endline should definetly always be the biggest thing found in the image if its there) 
3. Fit a polygon to that contour, you can extract out the number of sides from this
4. Check to see the number of sides is 4 and the ratio of length to width is that of a rectangle, and when this is found, set a internal flag to true indicating the endline has been seen
5. Keep running the algorithm until we finally don't see the endline in the frame anymore, at which point we check to see if we saw it in the last frame (flag will still be set to true), and at this point we know we have PASSED the endline and the service call to the supervisor node can be made to let it know

**Comment by y556zhao** [comment]
Quick Note: Steps to detect an endline:
1. filter for magenta
2. find all the contours in "images"
3. fit (approximate) polygons around all the contours 
4. find all the polygons that have four sides and the fit a rectangle around the polygons 
5. from the step 4, check the ratio of the width and height of rectangles
If it passes all the steps above, an endline is detected.
